### ISSUE TITLE
labelquant

### ISSUE THREAD

**Issue by why2kill** [prvst/philosopher#1]
Hi, 
I downloaded philosopher and completed the tutorial (database, comet search, peptideprophet, proteinprophet and report, etc).
However, when I wanna go further doing the quantification, it seemed to be unknown command "labelquant".
Had the labelquant functionality been implemented on philosopher yet?

**Comment by prvst** [comment]
Hi @why2kill ;

The public version doesn't have the labelquant command yet, we are working on that right now making sure that everything is working correctly. He hope to make it available soon with the next major release.
