### ISSUE TITLE
Filter and Report Throwing Errors

### ISSUE THREAD

**Issue by whitleyo** [prvst/philosopher#10]
Hi,

I'm trying to do an analysis of an ITRAQ labeled human proteome sample via MSFragger/Philosopher. The MSFragger search hits were able to successfully go through proteinprophet and peptideprophet, but I can't seem to get past the 'Filter' stage. I'm wondering what I might be doing wrong.

Here's my set of commands in my bash script:

./philosopher peptideprophet --database uniprot-reviewed_yes+taxonomy_9606_W_DECOYS_v3.fasta --nonparam --expectscore --decoy DECOY_ --decoyprobs --masswidth 500 --clevel 2 --forcedistr 053113_Wang_ITRAQ_1_search_3.pepXML
./philosopher proteinprophet interact-053113_Wang_ITRAQ_1_search_3.pep.xml --output interact-053113_Wang_ITRAQ_1_search_3.prot.xml
./philosopher filter --pepxml interact-053113_Wang_ITRAQ_1_search_3.pep.xml --protxml interact-053113_Wang_ITRAQ_1_search_3.prot.xml.prot.xml
./philosopher report

Here's where the FATAL messages start (upon starting filter):

INFO[16:45:24] Processing peptide identification files
INFO[16:45:27] 1+ Charge profile                             decoy=0 target=0
INFO[16:45:27] 2+ Charge profile                             decoy=0 target=2937
INFO[16:45:27] 3+ Charge profile                             decoy=0 target=1183
INFO[16:45:27] 4+ Charge profile                             decoy=0 target=644
INFO[16:45:27] 5+ Charge profile                             decoy=0 target=147
INFO[16:45:27] 6+ Charge profile                             decoy=0 target=27
INFO[16:45:27] Database search results                       ions=3682 peptides=3195 psms=4940
INFO[16:45:27] Converged to 0.00 % FDR with 4940 PSMs        decoy=0 threshold=-7 total=4940
INFO[16:45:27] Converged to 0.00 % FDR with 3195 Peptides    decoy=0 threshold=0.0503 total=3195
INFO[16:45:28] Converged to 0.00 % FDR with 3682 Ions        decoy=0 threshold=-7 total=3682
INFO[16:45:28] Protein inference results                     decoy=0 target=565
INFO[16:45:28] Converged to 0.00 % FDR with 549 Proteins     decoy=0 threshold=0.7228 total=549
INFO[16:45:28] 2D FDR estimation: Protein mirror image       decoy=549 target=549
INFO[16:45:28] Second filtering results                      ions=1444 peptides=1144 psms=2155
INFO[16:45:28] Converged to 0.00 % FDR with 2155 PSMs        decoy=0 threshold=-7 total=2155
INFO[16:45:29] Converged to 0.00 % FDR with 1144 Peptides    decoy=0 threshold=0.0558 total=1144
INFO[16:45:29] Converged to 0.00 % FDR with 1444 Ions        decoy=0 threshold=-7 total=1444
FATA[16:45:29] Database data not available, interrupting processing
FATA[16:45:29] cannot restore serialized data structures: invalid argument

**Comment by prvst** [comment]
Are you using the latest version ?
have you tried running `workspace --clean` and then starting again from the beginning ?

**Comment by whitleyo** [comment]
Tried 

rm -rf .meta (within my working directory)
./philosopher workspace --clean

followed by executing script again (but with ./philosopher workspace --init appended.

Still got the same output for filter:

INFO[14:07:28] Processing peptide identification files
INFO[14:07:32] 1+ Charge profile                             decoy=0 target=0
INFO[14:07:32] 2+ Charge profile                             decoy=0 target=2936
INFO[14:07:32] 3+ Charge profile                             decoy=0 target=1182
INFO[14:07:32] 4+ Charge profile                             decoy=0 target=646
INFO[14:07:32] 5+ Charge profile                             decoy=0 target=147
INFO[14:07:32] 6+ Charge profile                             decoy=0 target=27
INFO[14:07:32] Database search results                       ions=3684 peptides=3199 psms=4940
INFO[14:07:32] Converged to 0.00 % FDR with 4940 PSMs        decoy=0 threshold=-7 total=4940
INFO[14:07:32] Converged to 0.00 % FDR with 3199 Peptides    decoy=0 threshold=0.0502 total=3199
INFO[14:07:32] Converged to 0.00 % FDR with 3684 Ions        decoy=0 threshold=-7 total=3684
INFO[14:07:33] Protein inference results                     decoy=0 target=565
INFO[14:07:33] Converged to 0.00 % FDR with 549 Proteins     decoy=0 threshold=0.7227 total=549
INFO[14:07:33] 2D FDR estimation: Protein mirror image       decoy=549 target=549
INFO[14:07:33] Second filtering results                      ions=1444 peptides=1144 psms=2156
INFO[14:07:33] Converged to 0.00 % FDR with 2156 PSMs        decoy=0 threshold=-7 total=2156
INFO[14:07:33] Converged to 0.00 % FDR with 1144 Peptides    decoy=0 threshold=0.0558 total=1144
INFO[14:07:34] Converged to 0.00 % FDR with 1444 Ions        decoy=0 threshold=-7 total=1444
FATA[14:07:34] Database data not available, interrupting processing

**Comment by prvst** [comment]
Hey @whitleyo; we did several updates on the program lately, could you download the latest version and try doing your analysis again ? Also, have in mind that we do not have support for iTRAQ yet, only TMT.

This time, if you still have troubles, we have a way to investigate better what's going on with your analysis by looking into the meta data.

let me know if that works for you.
