### ISSUE TITLE
Print current version and build number when Philosopher is started

### ISSUE THREAD

**Issue by chhh** [prvst/philosopher#11]
Print the version when it's started without parameters or with some valid command. This makes easier debugging when something doesn't work for people and they just send you the output without running `philosopher version`.

**Comment by chhh** [comment]
I guess #14 sort of emphasizes that this is a very useful feature that is super simple to implement. Users do attach the output from their runs when something goes wrong, this way we: 
- Won't need to ask them about version
- Can be sure what version was actually running. They can send you the version from philosopher binary in their "/home/user/downloads" folder, but actually be using one that's in "/usr/bin" or something without realizing.

**Comment by prvst** [comment]
added to version 20180302
