### ISSUE TITLE
v2.0+ `mv` problems on Windows

### ISSUE THREAD

**Issue by chhh** [prvst/philosopher#12]
Looks like the `mv` command is not working for Windows users. From two reports on Fragger GUI repo, looks like it might be more Windows 7 specific.  

How do you unpack the tools that are used? Has it been changed since 1.9?

Reports:  
- chhh/MSFragger-GUI#37
- chhh/MSFragger-GUI#34

**Comment by prvst** [comment]
This issue was fixed on release [20180125](https://github.com/prvst/philosopher/releases/tag/20180125)
