### ISSUE TITLE
Philosopher report command fails at "Creating Protein FASTA report"

### ISSUE THREAD

**Issue by chhh** [prvst/philosopher#17]
Tried running with two small mzml files, just 1000 spectra in each. Philosopher report failed, see log below. 

Full log: [log_2018-02-28_15-05-03.txt](https://github.com/prvst/philosopher/files/1769195/log_2018-02-28_15-05-03.txt)

All the input files (mzml, fastsa, fragger.params) and the whole output directory are on the server in my data folder "for_felipe".

Short log:  
```
System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_144, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
MSFragger-GUI version 4.9
MSFragger version 20171106
Philosopher version 20180227 (build 201802271552)

Will execute 11 commands:
java -jar C:\data\andy\fragger-programs\MSFragger-20171106\MSFragger-20171106.jar C:\data\andy\fragger-gui-test-output-04\fragger.params C:\data\mzml\1000-scans-anonymous\file-001.mzML C:\data\mzml\1000-scans-anonymous\file-002.mzML 

java -cp C:\projects\msfragger-gui\MSFragger-GUI\build\classes umich.msfragger.util.FileMove C:\data\mzml\1000-scans-anonymous\file-001.pepXML C:\data\andy\fragger-gui-test-output-04\file-001.pepXML 

java -cp C:\projects\msfragger-gui\MSFragger-GUI\build\classes umich.msfragger.util.FileMove C:\data\mzml\1000-scans-anonymous\file-002.pepXML C:\data\andy\fragger-gui-test-output-04\file-002.pepXML 

C:\data\andy\fragger-programs\philosopher_windows_amd64_20180227.exe workspace --clean 

C:\data\andy\fragger-programs\philosopher_windows_amd64_20180227.exe workspace --init 

C:\data\andy\fragger-programs\philosopher_windows_amd64_20180227.exe peptideprophet --decoy rev --decoyprobs --ppm --accmass --nonparam --expectscore --database C:\data\andy\fasta\Uniprot.20151009.Hs.revDecoys.fa C:\data\andy\fragger-gui-test-output-04\file-001.pepXML 

C:\data\andy\fragger-programs\philosopher_windows_amd64_20180227.exe peptideprophet --decoy rev --decoyprobs --ppm --accmass --nonparam --expectscore --database C:\data\andy\fasta\Uniprot.20151009.Hs.revDecoys.fa C:\data\andy\fragger-gui-test-output-04\file-002.pepXML 

C:\data\andy\fragger-programs\philosopher_windows_amd64_20180227.exe proteinprophet --output interact interact-file-001.pep.xml interact-file-002.pep.xml 

C:\data\andy\fragger-programs\philosopher_windows_amd64_20180227.exe database --annotate C:\data\andy\fasta\Uniprot.20151009.Hs.revDecoys.fa 

C:\data\andy\fragger-programs\philosopher_windows_amd64_20180227.exe filter --sequential --pepxml C:\data\andy\fragger-gui-test-output-04 --protxml C:\data\andy\fragger-gui-test-output-04\interact.prot.xml 

C:\data\andy\fragger-programs\philosopher_windows_amd64_20180227.exe report 

~~~~~~~~~~~~~~~~~~~~~~

.....
.....
.....

INFO[15:02:39] Calculating Spectral Counts                  

INFO[15:02:39] Done                                         

Process finished, exit value: 0
Executing command:
$> C:\data\andy\fragger-programs\philosopher_windows_amd64_20180227.exe report 
Process started
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/prvst/philosopher/lib/rep.Run(0xc0420866f0, 0x24, 0xc042086720, 0x27, 0xc042098500, 0x46, 0xc04209a380, 0x36, 0xc042086750, 0x2d, ...)
	/home/felipevl/go/src/github.com/prvst/philosopher/lib/rep/rep.go:276 +0x703
github.com/prvst/philosopher/cmd.glob..func14(0x2c1c0a0, 0x2c3f208, 0x0, 0x0)
	/home/felipevl/go/src/github.com/prvst/philosopher/cmd/report.go:26 +0xea
github.com/spf13/cobra.(*Command).execute(0x2c1c0a0, 0x2c3f208, 0x0, 0x0, 0x2c1c0a0, 0x2c3f208)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:757 +0x2c8
github.com/spf13/cobra.(*Command).ExecuteC(0x2c1c300, 0xaf5b05, 0xc042091f78, 0x404083)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:843 +0x311
github.com/spf13/cobra.(*Command).Execute(0x2c1c300, 0x1, 0x0)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:791 +0x32
github.com/prvst/philosopher/cmd.Execute()
	/home/felipevl/go/src/github.com/prvst/philosopher/cmd/root.go:32 +0x34
main.main()
	/home/felipevl/go/src/github.com/prvst/philosopher/main.go:19 +0x77

INFO[15:02:39] Executing report                             
INFO[15:02:39] Creating Protein FASTA report                

Process finished, exit value: 2

```

**Comment by prvst** [comment]
I'll take a look a them for you today, but just looking at the output log I see that the PeptideProphet models failed for almost all the charge states, you have less than 200 PSMs in there. Also, try using the same decoy tag for both the filtering and the peptide validation, you have 'rev' for the validation and 'rev_' for the filtering.

**Comment by chhh** [comment]
- That's very likely there are very few PSMs, I just cut out a small portion of raw files to quickly test the whole pipeline from start to end. The goal is speed.
- That decoy tag - can you please explain what should it be set to in 1) *peptide prophet* and 2) *philosopher*? The way it's set up now is not just a coincidence, it's intentional based on some previous request. Should it just be `rev_` in both tools if sequences in the database look like:  
`>rev_sp|Q9NZ63|CI078_HUMAN Uncharacterized protein C9orf78 OS=Homo sapiens GN=C9orf78 PE=1 SV=1`

**Comment by prvst** [comment]
- I'm adding the error treatment for small lists on the next release, together wit the other suggestion you made before.

- if you have a decoy protein defined like this `>rev_sp|Q9NZ63|CI078_HUMAN Uncharacterized protein C9orf78 OS=Homo sapiens GN=C9orf78 PE=1 SV=1`, then you should use `rev_` everytime the tag is requested. The tag definition needs to be the same for all commands it is needed. If your protein is defined like this `>revsp|Q9NZ63|CI078_HUMAN Uncharacterized protein C9orf78 OS=Homo sapiens GN=C9orf78 PE=1 SV=1`, the you should use `rev`.

The tag is not only used for finding decoys on the fasta file, it is used internally for other purposes, that's why its important to have it defined exactly the same way every time it's requested.

**Comment by chhh** [comment]
Ok, that's much simpler than the way it is set up now. I'll sync the tag between all 3 commands.

**Comment by prvst** [comment]
You can add a text field to one of the GUI elements, like the one with the the search parameters, and then just use that for all the others commands, for example.

**Comment by chhh** [comment]
Yeah, maybe I'll do that too
