### ISSUE TITLE
Mapped Proteins, how to interpret result when decoy protein is mapped

### ISSUE THREAD

**Issue by pisistrato** [prvst/philosopher#19]
Hi again,

I have a question regarding the interpretation of the psm.tsv result.
For some psms in the file, in the Mapped Proteins column, one or multiple decoy proteins are reported e.g.

Peptide | Hyperscore | Nextscore | PeptideProphet Probability | Protein | Mapped Proteins
-- | -- | -- | -- | -- | --
KIQEESLR | 19.67 | 14.267 | 0.9997 | sp\|Q8R1B4\|EIF3C_MOUSE | rev_sp\|Q8R197\|SAST_MOUSE

How should one interpret this psm? I would think it should e filtered out because it is a decoy hit, but I am not sure as I would expect philosopher to remove it 'for me'.

Thanks

**Comment by prvst** [comment]
@pisistrato 

What you see there is a peptide that was assigned (i.e. mapping), to a _target_ protein. What you see on the __Mapped Proteins__ columns is the list of alternative proteins that also maps to the same peptide sequence, in this case a _decoy_. Judging only by the attributes we can see on your example, like the __PeptideProphet Probability__ ans the length of the sequence, this seems to be a confident hit and can be taken into consideration for downstream analysis.

**Comment by pisistrato** [comment]
Ok, thanks!
