### ISSUE TITLE
Wrong hint when illegal command is run

### ISSUE THREAD

**Issue by chhh** [prvst/philosopher#2]
Issued command:  
`/c/data/andy/fragger-programs/philosopher-source_windows_amd64.exe database --id UP000005640 --reviewed --contam
`  

Got:  
`FATA[16:51:29] Workspace not found. Run 'philosopher init' to create a workspace`  

`philosopher init` is not a valid command anymore.

Also, I tried calling `philospher workspace` when I was in a different directory from the executable and it didn't work.  
```
dmitr@chhh MINGW64 /c/data/fasta
$ ls -a
./  ../  ensembl_Homo_sapiens.GRCh38.pep.all.fa  uniprot-proteome_UP000005640_HUMAN.fasta  uniprot-proteome_UP000005640_HUMAN_concatenated_target_decoy.fasta

dmitr@chhh MINGW64 /c/data/fasta
$ ../andy/fragger-programs/philosopher_windows_amd64.exe workspace

dmitr@chhh MINGW64 /c/data/fasta
$ ls -a
./  ../  ensembl_Homo_sapiens.GRCh38.pep.all.fa  uniprot-proteome_UP000005640_HUMAN.fasta  uniprot-proteome_UP000005640_HUMAN_concatenated_target_decoy.fasta

dmitr@chhh MINGW64 /c/data/fasta
$ ../andy/fragger-programs/philosopher_windows_amd64.exe database --id UP000005640 --reviewed --contam
FATA[17:03:22] Workspace not found. Run 'philosopher init' to create a workspace
```

That's with version 1.1:
```
dmitr@chhh MINGW64 /c/data/fasta
$ ../andy/fragger-programs/philosopher_windows_amd64.exe
Philosopher: A tool for Proteomics data analysis and post-processing filtering
version: 1.1
...
```

**Comment by prvst** [comment]
The error message was fixed, should be available on the next release.

The workspace command does nothing without a parameter, and it does not need to be executed on the same folder the binary is. Try running `workspace --init` in the fasta folder before running the following commands.
