### ISSUE TITLE
Workspace init failed.

### ISSUE THREAD

**Issue by KaiLiCn** [prvst/philosopher#24]
Hi,

I can not build the work space by philosopher. Here is the output.

panic: Post https://www.google-analytics.com/collect: dial tcp: lookup www.google-analytics.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.

goroutine 1 [running]:
github.com/prvst/philosopher/cmd.init.17()
        /home/felipevl/go/src/github.com/prvst/philosopher/cmd/workspace.go:54 +0x4ac

My OS is Window 10. And the version of philosopher I used is "philosopher_windows_amd64.exe(20180530)".

**Comment by prvst** [comment]
have you tried again. that looks like an error from the on-line resource Philosopher queries for the analytics.
