### ISSUE TITLE
Pipeline example?

### ISSUE THREAD

**Issue by robert-winkler** [prvst/philosopher#27]
Hi Felipe, is there an example file for running a pipeline?
Ideally, it would write the results into the same directory.
Best, Robert

**Comment by prvst** [comment]
Hi;
Right now there is no example on the website, but I'm working on one, I'll post an udpate here once its ready.

**Comment by robert-winkler** [comment]
Thanks, Felipe! BTW: have you seen my invitation to write a book chapter about processing proteomics data with open software (Royal Society of Chemistry)?Best, RobertOn Nov 1, 2018 03:36, Felipe Leprevost <notifications@github.com> wrote:Hi;
Right now there is no example on the website, but I'm working on one, I'll post an udpate here once its ready.

**Comment by prvst** [comment]
Hi Robert;

I have not, could you please get in touch with me via email again ? please write to felipevl@umich.edu.

Thanks
