### ISSUE TITLE
latest commit wont download database

### ISSUE THREAD

**Issue by jgmeyerucsd** [prvst/philosopher#28]
tested latested commit with: 
philosopher.exe database --id [anyid] 

and it says its fetching but then it errors that it cannot find the file.  

The version from September works.

**Comment by prvst** [comment]
can you paste here the exact command you are trying to run, with the ID ?

**Comment by jgmeyerucsd** [comment]
any combination of commands I tried gives the error, for example:

philosopher_windows_amd64.exe database --id UP000005640 --contam --prefix rev_ 

The output says:
Executing Database 20181011
Fetching database
Processing decoys
Creating file
unable to parse the FASTA file: open: The system cannot find the file specified. 

My guess is an error with the tmp directory because it seems to spend the time downloading it and doing something to it before it quickly throws the error, and there is no file produced in the working directory.

**Comment by prvst** [comment]
The patch for the problem will be on the upcoming release, thanks for reporting the problem.
