### ISSUE TITLE
Enhancement - Spectral counting for each files in report

### ISSUE THREAD

**Issue by jspaezp** [prvst/philosopher#3]
This enhancement would be handy, as mentioned here:

https://github.com/chhh/MSFragger-GUI/issues/3

(in addition i was able to note that the latest release is supposed to integrate ptm-prophet, nonetheless i was not able to see it in any form of documentation)
Best ! (thanks for the piece of software)

**Comment by prvst** [comment]
What you are describing there is very similar to the abacus command, have you tried that ?
Regarding PTMProphet, we are still working on it.
