### ISSUE TITLE
Extended Mass Model, MSFragger/MSFragger-GUI

### ISSUE THREAD

**Issue by whitleyo** [prvst/philosopher#6]
Hi,

I'd like to do downstream analysis on an Msfragger generated pepxml file, and was wondering which utility out of philosopher implements the extended mass model described in Kong et al. 2017. Would it be correct to guess that it's done through the 'filter' program?

Thanks!

**Comment by prvst** [comment]
Hey @whitleyo 

The extended mass model mentioned in the article is implemented in the PetideProphet algorithm, provided by Philosopher. To take full advantage of the open search analysis, you need to follow up with the downstream analysis using Philosopher's version of the _Prophets_.
